
## numpy初学




In [1]:

%run my.py




In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import cv2


n  = np.random.randint(0,10 , size=(6,6))


n1 = n[::-1]
display(n,n1)

array([[2, 8, 4, 8, 3, 8],
       [7, 3, 1, 8, 4, 0],
       [3, 9, 2, 2, 1, 0],
       [4, 9, 2, 9, 7, 1],
       [2, 3, 8, 9, 7, 8],
       [7, 0, 1, 4, 3, 4]])

array([[7, 0, 1, 4, 3, 4],
       [2, 3, 8, 9, 7, 8],
       [4, 9, 2, 9, 7, 1],
       [3, 9, 2, 2, 1, 0],
       [7, 3, 1, 8, 4, 0],
       [2, 8, 4, 8, 3, 8]])

## 数据反转

In [4]:
fish = plt.imread('fish.png')
fish

array([[[0.29411766, 0.39215687, 0.46666667],
        [0.46666667, 0.4862745 , 0.49803922],
        [0.4627451 , 0.4862745 , 0.5019608 ],
        ...,
        [0.4627451 , 0.48235294, 0.49803922],
        [0.45882353, 0.47843137, 0.49803922],
        [0.21960784, 0.33333334, 0.44313726]],

       [[0.2901961 , 0.3764706 , 0.44313726],
        [0.627451  , 0.6156863 , 0.60784316],
        [0.85490197, 0.85490197, 0.84705883],
        ...,
        [0.8627451 , 0.85882354, 0.8509804 ],
        [0.8509804 , 0.8509804 , 0.84313726],
        [0.30588236, 0.42352942, 0.5254902 ]],

       [[0.28235295, 0.37254903, 0.4392157 ],
        [0.6666667 , 0.6627451 , 0.654902  ],
        [1.        , 1.        , 1.        ],
        ...,
        [1.        , 1.        , 1.        ],
        [1.        , 1.        , 1.        ],
        [0.35686275, 0.4745098 , 0.5764706 ]],

       ...,

       [[0.4509804 , 0.45882353, 0.45882353],
        [0.6509804 , 0.6509804 , 0.64705884],
        [0.99215686, 0

In [5]:
cat = plt.imread('cat.jpg')
cat.shape

(456, 730, 3)

In [8]:
#使用python语言的pillow 
from PIL import Image
cat = Image.open('cat.jpg')
cat
fish = Image.open('fish.png')

In [6]:

type(fish)
display(type(cat),type(fish))

numpy.ndarray

numpy.ndarray

In [3]:
n[:, 0:2]

array([[2, 2],
       [4, 8],
       [0, 2],
       [6, 9],
       [1, 3],
       [5, 2]])

In [ ]:
cat_cv = cv2.imread('cat.jpg')
cv2.imshow('cat',cat_cv)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
cat

In [8]:
def select(n):
    for i in range(len(n)):
        index = np.argmin(n[i:])
        n[index+i],n[i] = n[i],n[index+i]

n = np.array([6,1,2,5,4,3])
n
select(n)
n

        

array([1, 2, 3, 4, 5, 6])

In [13]:
n = np.array([5,2,4,6,7,1])
n 
np.sort(n)

array([1, 2, 4, 5, 6, 7])

 ## 减轻每一行的平均值


In [19]:
n = np.random.randint(0,10,size=(3,5))
n.mean(axis=1)
n - n.mean(axis=1).reshape(3,1)

array([[ 4.2, -1.8, -1.8,  1.2, -1.8],
       [ 2.2,  5.2, -1.8, -2.8, -2.8],
       [ 1.4,  2.4, -0.6,  1.4, -4.6]])

## 求最后两维的和

In [5]:
n = np.random.randint(0,10,size=(4,3,4,5))
n 





array([[[[9, 0, 4, 4, 5],
         [9, 8, 9, 0, 8],
         [5, 5, 6, 1, 6],
         [4, 8, 7, 9, 8]],

        [[4, 2, 0, 4, 2],
         [0, 8, 2, 0, 0],
         [5, 5, 1, 2, 1],
         [3, 6, 7, 6, 1]],

        [[0, 6, 4, 0, 3],
         [2, 4, 9, 1, 0],
         [0, 6, 7, 6, 7],
         [1, 0, 4, 9, 1]]],


       [[[7, 8, 0, 7, 2],
         [2, 5, 3, 2, 2],
         [4, 4, 9, 3, 6],
         [4, 9, 0, 0, 3]],

        [[8, 0, 6, 0, 3],
         [7, 9, 4, 1, 0],
         [2, 2, 7, 1, 3],
         [4, 6, 5, 1, 6]],

        [[7, 1, 3, 6, 2],
         [5, 7, 9, 0, 0],
         [0, 5, 1, 1, 6],
         [5, 0, 2, 4, 8]]],


       [[[8, 7, 8, 9, 8],
         [2, 6, 3, 1, 6],
         [2, 9, 3, 3, 6],
         [6, 2, 9, 2, 1]],

        [[5, 7, 8, 7, 1],
         [8, 7, 8, 7, 5],
         [7, 2, 5, 9, 2],
         [6, 3, 7, 0, 6]],

        [[8, 4, 1, 5, 6],
         [1, 6, 0, 0, 0],
         [0, 0, 1, 9, 6],
         [2, 4, 7, 7, 4]]],


       [[[5, 8, 0, 2, 7],
         [5, 8

In [6]:
np.sum(n,axis=(2,3))

array([[115,  59,  70],
       [ 80,  75,  72],
       [101, 110,  71],
       [ 83,  90,  73]])

In [7]:
np.sum(n,axis=(-1,-2))

array([[115,  59,  70],
       [ 80,  75,  72],
       [101, 110,  71],
       [ 83,  90,  73]])

In [8]:
np.sum(n,axis=(-2,-1))

array([[115,  59,  70],
       [ 80,  75,  72],
       [101, 110,  71],
       [ 83,  90,  73]])

## 交换两行

In [9]:
n1 = np.random.randint(0,10,size=(4,5))
n1

array([[4, 4, 4, 1, 2],
       [7, 1, 6, 9, 2],
       [8, 4, 7, 8, 3],
       [9, 6, 0, 6, 2]])

In [11]:
n1[[0,1]] 

array([[4, 4, 4, 1, 2],
       [7, 1, 6, 9, 2]])

In [12]:
n1[[0,1]] = n1[[1,0]]
n1

array([[7, 1, 6, 9, 2],
       [4, 4, 4, 1, 2],
       [8, 4, 7, 8, 3],
       [9, 6, 0, 6, 2]])

## 矩阵减去每一行的平均值

In [13]:
n2 = np.random.randint(0,10,size=(3,5))
n2

array([[5, 6, 6, 1, 3],
       [8, 6, 1, 9, 8],
       [1, 8, 1, 1, 8]])

In [15]:
n2.mean(axis=1)

array([4.2, 6.4, 3.8])

In [18]:
n2 - n2.mean(axis=1).reshape(3,-1)

array([[ 0.8,  1.8,  1.8, -3.2, -1.2],
       [ 1.6, -0.4, -5.4,  2.6,  1.6],
       [-2.8,  4.2, -2.8, -2.8,  4.2]])

In [19]:
n2.mean(axis=1).reshape(3,-1)

array([[4.2],
       [6.4],
       [3.8]])