In [1]:
import numpy as np

## 1、冒泡排序

In [14]:
def bubble_sort(arr):
    length = len(arr)
    for i in range(length-1):
        #优化，如果没发生交换说明数组本身有序，属于好的情况时间复杂度为O(n)
        switched = False
        for j in range(length-i-1):
            if arr[j] > arr[j+1]:
                arr[j],arr[j+1] = arr[j+1],arr[j]
                switched = True
        if not switched:
            break
    return arr      

In [27]:
arr = np.array([1,4,2,7,3,0,5])
bubble_sort(arr)


array([0, 1, 2, 3, 4, 5, 7])

## 2、选择排序

In [20]:
def selection_sort(arr):
    length = len(arr)
    for i in range(length-1):
        minIndex = i
        for j in range(i+1,length-1):
            if(arr[minIndex] > arr[j]):
                minIndex = j
        arr[i],arr[minIndex] = arr[minIndex],arr[i]
    return arr


In [21]:
arr = np.array([1,4,2,7,3,0,5])
selection_sort(arr)

array([0, 1, 2, 3, 4, 7, 5])

In [28]:
def select_sort(arr):
    for i in range(len(arr)):
        #使用numpy中的argmin函数获取最小值索引S
        index = np.argmin(arr[i:])+i
        arr[index],arr[i] = arr[i],arr[index]
    return arr

In [29]:
arr = np.array([1,4,2,7,3,0,5])
select_sort(arr)

array([0, 1, 2, 3, 4, 5, 7])

## 3、快速排序

In [22]:
def quick_sort(arr):
    if len(arr) < 2:
        return arr
    #选择基准值
    pivot = arr.pop()
    greater = []
    less = []
    
    for i in range(len(arr)):
        if arr[i] > pivot:
            greater.append(arr[i])
        else:
            less.append(arr[i])
    return quick_sort(less) + [pivot] + quick_sort(greater)
    

In [24]:
arr = [1,4,2,7,3,0,5]
quick_sort(arr)

[0, 1, 2, 3, 4, 5, 7]

## 4、插入排序

In [25]:
def insert_sort(arr):
    for i in range(1,len(arr)):
        loop_index = i
        while loop_index > 0 and arr[loop_index] < arr[loop_index-1]:
            arr[loop_index],arr[loop_index-1] = arr[loop_index-1],arr[loop_index]
            loop_index -= 1
    return arr


In [26]:
arr = [1,4,2,7,3,0,5]
insert_sort(arr)

[0, 1, 2, 3, 4, 5, 7]

## 使用numpy的包排序

In [32]:
n = np.random.randint(0,100,size=100)
n

array([48, 77, 78, 35, 37, 38, 75, 78, 38, 36, 15, 88, 79, 48, 65, 73,  6,
       73,  9, 79, 12, 61, 25, 79, 61, 75, 40, 99, 15, 97, 41, 59, 57, 10,
       59, 75, 72, 30, 62, 95, 26, 14, 85, 35, 64, 91, 69, 25, 65, 19, 79,
       23, 72, 33, 47, 40, 39, 36, 28, 55, 17, 69, 94, 81, 11, 74, 84, 40,
       56, 87, 58, 77, 57, 82, 90, 21, 40,  5, 72, 68, 54, 69,  4, 60, 12,
       43, 98, 41,  5, 69, 87,  1, 50, 42, 69, 25, 71, 44, 14, 46])

In [34]:
np.partition(n,kth=5)

array([ 4,  1,  5,  6,  5,  9, 12, 12, 10, 11, 14, 42, 15, 36, 41, 43, 38,
       25, 44, 38, 19, 37, 25, 40, 21, 40, 40, 35, 15, 17, 41, 28, 36, 14,
       39, 40, 33, 30, 23, 25, 26, 35, 46, 85, 64, 91, 69, 95, 65, 77, 79,
       62, 72, 72, 47, 75, 59, 57, 59, 55, 97, 69, 94, 81, 99, 74, 84, 75,
       56, 87, 58, 77, 57, 82, 90, 61, 79, 61, 72, 68, 54, 69, 79, 60, 73,
       73, 98, 65, 48, 69, 87, 79, 50, 88, 69, 78, 71, 75, 78, 48])

In [35]:
np.partition(n,kth=-5)

array([35, 19, 14, 35, 37, 38, 44, 25, 38, 36, 15, 42,  1,  5, 41, 43,  6,
       12,  9,  4, 12,  5, 25, 40, 21, 40, 40, 11, 15, 17, 41, 28, 36, 10,
       39, 40, 33, 30, 23, 25, 26, 14, 46, 72, 48, 75, 69, 71, 65, 69, 50,
       62, 72, 72, 47, 75, 59, 57, 59, 55, 69, 69, 48, 65, 73, 74, 73, 75,
       56, 60, 58, 64, 57, 69, 54, 61, 68, 61, 77, 79, 79, 82, 79, 78, 84,
       78, 77, 81, 79, 85, 90, 88, 87, 87, 91, 94, 95, 97, 99, 98])