In [121]:
import numpy as np

X = np.array([[  0 ,14 , 8 ,  0 ,  5,  -2,   9,  -3],
 [ -4 , 10 ,  6 ,  4 ,-14 , -2 ,-14  , 8],
 [ -1 , -6  , 5 ,-12 ,  3 , -3 ,  2 , -2],
 [  5 , -2  , 3 , 10  , 5 , 11 ,  4  ,-8],
 [-15 ,-15  ,-8 ,-15 ,  7 , -4, -12 ,  2],
 [ 11 ,-10 , -2 ,  4  , 3 , -9 , -6 ,  7],
 [-14 ,  0 ,  4 , -3  , 5 , 10 , 13 ,  7],
 [ -3 , -7 , -2 , -8  , 0 , -6 , -5 , -9]])

y = np.array([ 339 ,-114  , 30 , 126, -395 , -87 , 422, -309])

y

array([ 339, -114,   30,  126, -395,  -87,  422, -309])

In [122]:
from IPython.core.display import display
from sklearn.linear_model import LinearRegression
w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
w


array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12.])

In [123]:
mode = LinearRegression(fit_intercept=False)
mode.fit(X,y)
display(mode.coef_,mode.intercept_)

array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12.])

0.0

array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12.])

0.0

In [124]:
y_new = y+64
y_new

array([ 403,  -50,   94,  190, -331,  -23,  486, -245])

array([ 403,  -50,   94,  190, -331,  -23,  486, -245])

In [125]:
w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y_new)
w


array([-9.53423295, -3.18237714, 32.89293368, 13.94370726, 12.88345187,
       -5.64066992, 14.95379584,  8.62431708])

array([-9.53423295, -3.18237714, 32.89293368, 13.94370726, 12.88345187,
       -5.64066992, 14.95379584,  8.62431708])

In [126]:
X_new = np.concatenate([X,np.ones(shape=(8,1))],axis=1)
X_new

array([[  0.,  14.,   8.,   0.,   5.,  -2.,   9.,  -3.,   1.],
       [ -4.,  10.,   6.,   4., -14.,  -2., -14.,   8.,   1.],
       [ -1.,  -6.,   5., -12.,   3.,  -3.,   2.,  -2.,   1.],
       [  5.,  -2.,   3.,  10.,   5.,  11.,   4.,  -8.,   1.],
       [-15., -15.,  -8., -15.,   7.,  -4., -12.,   2.,   1.],
       [ 11., -10.,  -2.,   4.,   3.,  -9.,  -6.,   7.,   1.],
       [-14.,   0.,   4.,  -3.,   5.,  10.,  13.,   7.,   1.],
       [ -3.,  -7.,  -2.,  -8.,   0.,  -6.,  -5.,  -9.,   1.]])

array([[  0.,  14.,   8.,   0.,   5.,  -2.,   9.,  -3.,   1.],
       [ -4.,  10.,   6.,   4., -14.,  -2., -14.,   8.,   1.],
       [ -1.,  -6.,   5., -12.,   3.,  -3.,   2.,  -2.,   1.],
       [  5.,  -2.,   3.,  10.,   5.,  11.,   4.,  -8.,   1.],
       [-15., -15.,  -8., -15.,   7.,  -4., -12.,   2.,   1.],
       [ 11., -10.,  -2.,   4.,   3.,  -9.,  -6.,   7.,   1.],
       [-14.,   0.,   4.,  -3.,   5.,  10.,  13.,   7.,   1.],
       [ -3.,  -7.,  -2.,  -8.,   0.,  -6.,  -5.,  -9.,   1.]])

In [127]:
X_new.shape

(8, 9)

(8, 9)

In [128]:
w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y_new)
w


array([-9.53423295, -3.18237714, 32.89293368, 13.94370726, 12.88345187,
       -5.64066992, 14.95379584,  8.62431708])

array([-9.53423295, -3.18237714, 32.89293368, 13.94370726, 12.88345187,
       -5.64066992, 14.95379584,  8.62431708])

In [129]:
w = np.array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12.])
b = 64
X9= np.random.randint(-10,10,size=8)
y9 = w.dot(X9) +b
y9

y_new = np.concatenate([y_new,[y9]])
y_new

array([ 403.,  -50.,   94.,  190., -331.,  -23.,  486., -245., -229.])

array([ 403.,  -50.,   94.,  190., -331.,  -23.,  486., -245., -264.])

In [130]:
X_new = np.concatenate([X_new,[np.concatenate([X9,[1]])]])
X_new

array([[  0.,  14.,   8.,   0.,   5.,  -2.,   9.,  -3.,   1.],
       [ -4.,  10.,   6.,   4., -14.,  -2., -14.,   8.,   1.],
       [ -1.,  -6.,   5., -12.,   3.,  -3.,   2.,  -2.,   1.],
       [  5.,  -2.,   3.,  10.,   5.,  11.,   4.,  -8.,   1.],
       [-15., -15.,  -8., -15.,   7.,  -4., -12.,   2.,   1.],
       [ 11., -10.,  -2.,   4.,   3.,  -9.,  -6.,   7.,   1.],
       [-14.,   0.,   4.,  -3.,   5.,  10.,  13.,   7.,   1.],
       [ -3.,  -7.,  -2.,  -8.,   0.,  -6.,  -5.,  -9.,   1.],
       [  1.,  -5.,  -6.,   9., -10.,  -3.,  -6.,  -1.,   1.]])

array([[  0.,  14.,   8.,   0.,   5.,  -2.,   9.,  -3.,   1.],
       [ -4.,  10.,   6.,   4., -14.,  -2., -14.,   8.,   1.],
       [ -1.,  -6.,   5., -12.,   3.,  -3.,   2.,  -2.,   1.],
       [  5.,  -2.,   3.,  10.,   5.,  11.,   4.,  -8.,   1.],
       [-15., -15.,  -8., -15.,   7.,  -4., -12.,   2.,   1.],
       [ 11., -10.,  -2.,   4.,   3.,  -9.,  -6.,   7.,   1.],
       [-14.,   0.,   4.,  -3.,   5.,  10.,  13.,   7.,   1.],
       [ -3.,  -7.,  -2.,  -8.,   0.,  -6.,  -5.,  -9.,   1.],
       [  3., -10.,  -9.,   8.,   9.,   6., -10.,  -8.,   1.]])

In [131]:
mode = LinearRegression(fit_intercept=False)
mode.fit(X_new,y_new)
display(mode.coef_,mode.intercept_)



array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12., 64.])

0.0

array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12., 64.])

0.0

In [132]:
mode = LinearRegression(fit_intercept=True)
mode.fit(X_new,y_new)
display(mode.coef_,mode.intercept_)


array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12.,  0.])

64.00000000000036

array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12.,  0.])

64.0000000000003

In [133]:
w = np.linalg.inv(X_new.T.dot(X_new)).dot(X_new.T).dot(y_new)
w


array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12., 64.])

array([ 1.,  5., 15.,  3.,  8.,  4., 17., 12., 64.])